# Generated by Django 3.2.3 on 2021-05-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('gender', models.CharField(choices=[('unknown', '不明'), ('man', '男'), ('woman', '女')], max_length=7)),
                ('discription', models.CharField(max_length=1000, verbose_name='説明')),
            ],
        ),
    ]
