# Generated by Django 3.2.3 on 2021-05-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='gender',
            field=models.CharField(choices=[('', '性別を選んでください'), ('unknown', '不明'), ('man', '男'), ('woman', '女')], max_length=7),
        ),
    ]
