# Generated by Django 3.2.3 on 2021-05-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_characters_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='gender',
            field=models.CharField(choices=[('', '性別を選んでください'), ('unknown', '不明'), ('man', '男'), ('woman', '女')], max_length=7, verbose_name='性別'),
        ),
    ]
