# Generated by Django 3.2.3 on 2021-05-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20210518_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='discription',
            field=models.CharField(max_length=1000, verbose_name='特徴'),
        ),
    ]
