# Generated by Django 3.2.3 on 2021-05-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('username', models.CharField(default='匿名ユーザー', max_length=30)),
                ('zipcode', models.CharField(default='郵便番号', max_length=8)),
                ('prefecture', models.CharField(default='都道府県', max_length=5)),
                ('city', models.CharField(default='市町村', max_length=100)),
                ('address', models.CharField(default='建物名', max_length=200)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
